# Generated by Django 4.2.5 on 2023-12-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmail', models.CharField(max_length=255)),
                ('lpasswd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200, null=True)),
                ('remail', models.CharField(max_length=200)),
                ('rpass', models.CharField(max_length=200, null=True)),
                ('rrpass', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
