# Generated by Django 4.2.5 on 2024-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userage', models.IntegerField(max_length=100)),
                ('usernumber', models.BigIntegerField(max_length=100)),
                ('userfile', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
    ]
