# Generated by Django 4.2.5 on 2024-01-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_mprofile_userimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprofile',
            name='userimg',
        ),
    ]
