# Generated by Django 4.2.5 on 2024-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_mprofile_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofile',
            name='userage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mprofile',
            name='usernumber',
            field=models.IntegerField(null=True),
        ),
    ]
