# Generated by Django 4.2.5 on 2024-02-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_usymptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='usymptoms',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
