# Generated by Django 4.2.5 on 2024-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_usymptoms_userchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userheight', models.IntegerField(null=True)),
                ('userweight', models.IntegerField(null=True)),
                ('userchat', models.TextField(blank=True, null=True)),
                ('userfile', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usymptoms',
        ),
    ]
