# Generated by Django 4.2.5 on 2024-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_symptom_delete_usymptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='userfile',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
