# Generated by Django 4.2.5 on 2024-02-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_symptom_userfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
