# Generated by Django 4.2.5 on 2024-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_rename_register_user_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mprofile',
        ),
        migrations.AddField(
            model_name='user',
            name='rage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rnumber',
            field=models.IntegerField(null=True),
        ),
    ]
