# Generated by Django 4.2.5 on 2024-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_delete_mprofile_user_rage_user_rnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userage', models.IntegerField(null=True)),
                ('usernumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='rage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rnumber',
        ),
    ]
