# Generated by Django 4.2.5 on 2024-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_mprofile_remove_user_rage_remove_user_rnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mprofile',
        ),
        migrations.AddField(
            model_name='user',
            name='rage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rnumber',
            field=models.IntegerField(null=True),
        ),
    ]
