# Generated by Django 3.2.9 on 2024-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_delete_mprofile_user_rage_user_rnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
