# Generated by Django 5.0.2 on 2024-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_user_remail'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='userage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='userbg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
