# Generated by Django 4.2.5 on 2024-04-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_symptom_userage_symptom_userbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=200, null=True)),
                ('ademail', models.CharField(max_length=200, null=True)),
                ('adpass', models.CharField(max_length=200, null=True)),
                ('adrepass', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='userbg',
            new_name='symtuseremail',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='userage',
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptomurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
